<a href="https://colab.research.google.com/github/sricheru/pytorch-tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch

#Addition
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([2,3,4,5,6])

tensor_a + tensor_b

tensor([ 3,  5,  7,  9, 11])

In [7]:
tensor_add = torch.add(tensor_a,tensor_b)
tensor_add

tensor([ 3,  5,  7,  9, 11])

In [8]:
#Sub
torch.subtract(tensor_a,tensor_b)

tensor([-1, -1, -1, -1, -1])

In [10]:
torch.multiply(tensor_a,tensor_b)

tensor([ 2,  6, 12, 20, 30])